### ISSUE TITLE
admin 페이지 수정

### ISSUE THREAD

**Issue by ujeongoh** [devcombine/devcombine#40]
### Issue 타입 ('x' 로 표기)
- [ ] 기능 추가
- [x] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 문서 작성 및 수정

### 상세 내용
- admin페이지 출력 양식을 수정합니다.

### 예상 소요 시간
- [ ] `0.5h`
- [ ] `1h`
- [x] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by sejeong-park** [comment]
@ujeongoh 유정님, 이거 생성 해주신건가요?
feature/app 가보시면 현재 작업까지 업데이트 했는데, 확인해주세요!
